### ISSUE TITLE
auto generate "options" property in manifest.json file when build

### ISSUE THREAD

**Issue by Benbinbin** [yeqisong/vite-plugin-vue-crx3#1]
Refer to the [documentation](https://developer.chrome.com/docs/extensions/mv2/options/), I use the `"options_page": ./options.html` property in `maifest.json` file, to provide a options page for user to customise the behavior of an extension. 

When I build the extension, the `manifest.json` file remain the `"options_page": ./options.html` property, but at the same time it will auto generate the `"options": options.html` property, which cause an error.

**Comment by yeqisong** [comment]
The bug has been fixed. In the distDir method under the 'src/processors/html.js/distDir' directory, change the keyword options to options_page.
